"""Initial migration

Revision ID: 3424755854ac
Revises: 9da7a420221b
Create Date: 2025-02-12 20:55:54.634602+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3424755854ac'
down_revision: Union[str, None] = '9da7a420221b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schools_id', table_name='schools')
    op.drop_index('ix_schools_name', table_name='schools')
    op.drop_table('schools')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_clusters_id', table_name='clusters')
    op.drop_table('clusters')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('qualification_type', sa.VARCHAR(), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clusters_id', 'clusters', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('schools',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('level', sa.VARCHAR(), nullable=False),
    sa.Column('location', sa.VARCHAR(), nullable=False),
    sa.Column('studentt_count', sa.INTEGER(), nullable=False),
    sa.Column('male_female_ratio', sa.VARCHAR(), nullable=False),
    sa.Column('teacher_count', sa.INTEGER(), nullable=False),
    sa.Column('student_age_range', sa.VARCHAR(), nullable=False),
    sa.Column('cluster_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schools_name', 'schools', ['name'], unique=1)
    op.create_index('ix_schools_id', 'schools', ['id'], unique=False)
    # ### end Alembic commands ###
